name: 'spring-boot-microservices'
services:
  catalog-db: #helps spin up a container for postgres catalog-db, this can be different for different databases
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m #m here means Mebibytes 1 MiB (mebibyte) = 1,048,576 bytes